-- Fix mindmaps INSERT policy to require admin role (content is generated by edge functions with service role)
DROP POLICY IF EXISTS "Authenticated users can create mindmaps" ON public.mindmaps;

CREATE POLICY "Only admins can create mindmaps directly"
ON public.mindmaps FOR INSERT
TO authenticated
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- Add DELETE policy for admins on mindmaps
CREATE POLICY "Admins can delete mindmaps"
ON public.mindmaps FOR DELETE
TO authenticated
USING (has_role(auth.uid(), 'admin'::app_role));

-- Add UPDATE policy for admins on mindmaps
CREATE POLICY "Admins can update mindmaps"
ON public.mindmaps FOR UPDATE
TO authenticated
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- Fix infographics INSERT policy to require admin role (content is generated by edge functions with service role)
DROP POLICY IF EXISTS "Authenticated users can create infographics" ON public.infographics;

CREATE POLICY "Only admins can create infographics directly"
ON public.infographics FOR INSERT
TO authenticated
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- Fix infographics UPDATE policy to require admin role
DROP POLICY IF EXISTS "Authenticated users can update infographics" ON public.infographics;

CREATE POLICY "Only admins can update infographics directly"
ON public.infographics FOR UPDATE
TO authenticated
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- Add DELETE policy for admins on infographics
CREATE POLICY "Admins can delete infographics"
ON public.infographics FOR DELETE
TO authenticated
USING (has_role(auth.uid(), 'admin'::app_role));